#  PARAMETERS.
#  - Introduction guide: 'https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started'.
---
parameters:
  menu_options:
    '1': ['USD', 'ARS']
    '2': ['ARS', 'USD']
    '3': ['USD', 'BRL']
    '4': ['BRL', 'USD']
    '5': ['USD', 'COP']
    '6': ['COP', 'USD']
# EOF.